export const LANGUAGES = [
    {text: "עברית", value: "HEB"},
    {text: "אנגלית", value: "ENG"},
    {text: "רוסית", value: "RUS"},
    {text: "ספרדית", value: "SPA"},
    {text: "אוקראינית", value: "UKR"},
    {text: "איטלקית", value: "ITA"},
    {text: "גרמנית", value: "GER"},
    {text: "הולנדית", value: "DUT"},
    {text: "צרפתית", value: "FRE"},
    {text: "פורטוגזית", value: "POR"},
    {text: "טורקית", value: "TRK"},
    {text: "פולנית", value: "POL"},
    {text: "ערבית", value: "ARB"},
    {text: "הונגרית", value: "HUN"},
    {text: "פינית", value: "FIN"},
    {text: "ליטאית", value: "LIT"},
    {text: "יפנית", value: "JPN"},
    {text: "בולגרית", value: "BUL"},
    {text: "גאורגית", value: "GEO"},
    {text: "נורבגית", value: "NOR"},
    {text: "שבדית", value: "SWE"},
    {text: "קרואטית", value: "HRV"},
    {text: "סינית", value: "CHN"},
    {text: "פרסית", value: "FAR"},
    {text: "רומנית", value: "RON"},
    {text: "הינדי", value: "HIN"},
    {text: "מקדונית", value: "MKD"},
    {text: "סלובנית", value: "SLV"},
    {text: "לטבית", value: "LAV"},
    {text: "סלובקית", value: "SLK"},
    {text: "צ'כית", value: "CZE"},
];

export const MDB_LANGUAGES = {
    "en": "ENG",
    "he": "HEB",
    "ru": "RUS",
    "es": "SPA",
    "it": "ITA",
    "de": "GER",
    "nl": "DUT",
    "fr": "FRE",
    "pt": "POR",
    "tr": "TRK",
    "pl": "POL",
    "ar": "ARB",
    "hu": "HUN",
    "fi": "FIN",
    "lt": "LIT",
    "ja": "JPN",
    "bg": "BUL",
    "ka": "GEO",
    "no": "NOR",
    "sv": "SWE",
    "hr": "HRV",
    "zh": "CHN",
    "fa": "FAR",
    "ro": "RON",
    "hi": "HIN",
    "mk": "MKD",
    "sl": "SLV",
    "lv": "LAV",
    "sk": "SLK",
    "cs": "CZE",
    "ua": "UKR",
    "zz": "MLT",
    "xx": "UNK",
};

export const LECTURERS = [
    {text: "רב", value: "rav"},
    {text: "בלי רב", value: "norav"},
];