export const LANGUAGES = [
    {text: "עברית", value: "heb"},
    {text: "אנגלית", value: "eng"},
    {text: "רוסית", value: "rus"},
    {text: "ספרדית", value: "spa"},
    {text: "אוקראינית", value: "ukr"},
    {text: "איטלקית", value: "ita"},
    {text: "גרמנית", value: "ger"},
    {text: "הולנדית", value: "dut"},
    {text: "צרפתית", value: "FRE"},
    {text: "פורטוגזית", value: "por"},
    {text: "טורקית", value: "trk"},
    {text: "פולנית", value: "pol"},
    {text: "ערבית", value: "arb"},
    {text: "הונגרית", value: "hun"},
    {text: "פינית", value: "fin"},
    {text: "ליטאית", value: "lit"},
    {text: "יפנית", value: "jpn"},
    {text: "בולגרית", value: "bul"},
    {text: "גאורגית", value: "geo"},
    {text: "נורבגית", value: "nor"},
    {text: "שבדית", value: "swe"},
    {text: "קרואטית", value: "hrv"},
    {text: "סינית", value: "chn"},
    {text: "פרסית", value: "far"},
    {text: "רומנית", value: "ron"},
    {text: "הינדי", value: "hin"},
    {text: "מקדונית", value: "mkd"},
    {text: "סלובנית", value: "slv"},
    {text: "לטבית", value: "lav"},
    {text: "סלובקית", value: "slk"},
    {text: "צ'כית", value: "cze"},
];

export const MDB_LANGUAGES = {
    "en": "eng",
    "he": "heb",
    "ru": "rus",
    "es": "spa",
    "it": "ita",
    "de": "ger",
    "nl": "dut",
    "fr": "fre",
    "pt": "por",
    "tr": "trk",
    "pl": "pol",
    "ar": "arb",
    "hu": "hun",
    "fi": "fin",
    "lt": "lit",
    "ja": "jpn",
    "bg": "bul",
    "ka": "geo",
    "no": "nor",
    "sv": "swe",
    "hr": "hrv",
    "zh": "chn",
    "fa": "far",
    "ro": "ron",
    "hi": "hin",
    "mk": "mkd",
    "sl": "slv",
    "lv": "lav",
    "sk": "slk",
    "cs": "cze",
    "ua": "ukr",
    "zz": "mlt",
    "xx": "unk",
};

export const LECTURERS = [
    {text: "רב", value: "rav"},
    {text: "בלי רב", value: "norav"},
];